---
apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
  namespace: default
  labels:
    app: frontend-v2
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: frontend-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-v2
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend-v2
  namespace: default
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-v2
      app: frontend-v2
  template:
    metadata:
      labels:
        service: frontend-v2
        app: frontend-v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "public-api:8080"
        consul.hashicorp.com/service-meta-version: "v2"
    spec:
      serviceAccountName: frontend-v2
      containers:
        - name: frontend-v2
          image: hashicorpdemoapp/frontend:v1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NEXT_PUBLIC_PUBLIC_API_URL
              value: "/"
            - name: NEXT_PUBLIC_FOOTER_FLAG
              value: "HashiCups-v2"